# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - main
  paths:
    include:
      - Frontend/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: NODE_VERSION
    value: '18.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'
  displayName: 'Install Node.js'

- script: |
    cd Frontend
    npm install
  displayName: 'npm install'

- script: |
    cd Frontend
    npm run build
  displayName: 'npm build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Frontend/build'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts' 